import type { Icon } from "@phosphor-icons/react";
import {
  ArrowsLeftRight,
  Atom,
  Calculator,
  CaretRight,
  Check,
  CheckCircle,
  CheckSquare,
  Clock,
  ClockCounterClockwise,
  Copy,
  Database,
  Download,
  Drop,
  Eyedropper,
  BookOpen,
  FileCsv,
  FileText,
  Flask,
  FloppyDisk,
  GearSix,
  Info,
  List,
  ListChecks,
  Lock,
  MagicWand,
  MagnifyingGlass,
  Plus,
  Printer,
  Question,
  Scales,
  ShieldCheck,
  Spinner,
  Square,
  SquaresFour,
  Table,
  TestTube,
  Trash,
  Warning,
  WarningCircle,
  X,
} from "@phosphor-icons/react";

export type AppIcon = Icon;
export type LucideIcon = Icon;

export {
  ArrowsLeftRight as ArrowRightLeft,
  Atom,
  Calculator,
  CaretRight as ChevronRight,
  Check,
  CheckCircle as CheckCircle2,
  CheckSquare,
  Clock,
  ClockCounterClockwise as History,
  Copy,
  Database,
  Download,
  Drop as Droplets,
  BookOpen,
  BookOpen as Book,
  Eyedropper as Pipette,
  FileCsv as FileSpreadsheet,
  FileText,
  Flask as FlaskConical,
  FloppyDisk as Save,
  GearSix as Settings,
  GearSix as Settings2,
  Info,
  List as Menu,
  ListChecks,
  Lock,
  MagicWand as WandSparkles,
  MagnifyingGlass as Search,
  Plus,
  Printer,
  Question as HelpCircle,
  Scales as Scale,
  ShieldCheck,
  Spinner as Loader2,
  Square,
  SquaresFour as LayoutGrid,
  Table as Table2,
  TestTube as Beaker,
  Trash as Trash2,
  Warning as AlertTriangle,
  WarningCircle as AlertCircle,
  X,
};
